apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exo
resources:
  - ../ai
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: exo
    path: tailscale-patch.yaml
