apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exo
  namespace: exo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: exo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: exo
                port:
                  number: 52415
